name: Pull Request Stats

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          # repositories: 'OrangeScape/kf-xg-frontend'
          webhook: 'https://pr-stats.deveditor.workers.dev/pr-stats/api/githook?repo=kissflow/lcnc-sdk-js'